FROM ubuntu:22.04
RUN apt-get update && apt-get install -y --no-install-recommends software-properties-common && \
    apt-get -y --no-install-recommends install \
    build-essential \
    cmake \
    g++ \
    gcc \
    git \
    libarmadillo-dev \
    libbladerf-dev \
    libboost-all-dev \
    libev-dev \
    libfftw3-dev \
    libgmp-dev \
    libgsl-dev \
    liblimesuite-dev \
    liblog4cpp5-dev \
    libpython3-dev \
    libspdlog-dev \
    libthrift-dev \
    libuhd-dev \
    libunwind-dev \
    libusb-1.0-0-dev \
    libusb-1.0-0 \
    libvulkan-dev \
    libzmq3-dev \
    make \
    netcat \
    pkg-config \
    python3-bladerf \
    python3-mako \
    python3-numpy \
    python3-packaging \
    python3-pip \
    python3-pygccxml \
    python3-uhd \
    python3-zmq \
    sudo \
    swig \
    uhd-host \
    unzip \
    wget
RUN /usr/lib/uhd/utils/uhd_images_downloader.py -t "b2|usb"
WORKDIR /root
# https://wiki.gnuradio.org/index.php/GNU_Radio_3.9_OOT_Module_Porting_Guide
RUN git clone --depth 1 https://github.com/pybind/pybind11 -b v2.11.1
RUN git clone --depth 1 https://github.com/gnuradio/volk -b v3.0.0
RUN git clone --depth 1 https://github.com/pothosware/SoapySDR -b soapy-sdr-0.8.1
WORKDIR /root/pybind11/build
RUN cmake -DPYBIND11_TEST="" .. && make -j "$(nproc)" && make install
WORKDIR /root/volk/build
RUN git submodule update --init
RUN cmake .. && make -j "$(nproc)" && make install
WORKDIR /root/SoapySDR/build
RUN cmake .. && make -j "$(nproc)" && make install
