FROM ubuntu:24.04
RUN apt-get update && apt-get install -y --no-install-recommends software-properties-common && \
    apt-get -y --no-install-recommends install \
    build-essential \
    cmake \
    cppzmq-dev \
    g++ \
    gcc \
    git \
    libarmadillo-dev \
    libbladerf-dev \
    libboost-all-dev \
    libev-dev \
    libfftw3-dev \
    libgmp-dev \
    libgsl-dev \
    liblimesuite-dev \
    liblog4cpp5-dev \
    libpython3-dev \
    libspdlog-dev \
    libthrift-dev \
    libuhd-dev \
    libunwind-dev \
    libusb-1.0-0-dev \
    libusb-1.0-0 \
    libvulkan-dev \
    libzmq3-dev \
    make \
    netcat-traditional \
    pkg-config \
    pybind11-dev \
    python3-bladerf \
    python3-mako \
    python3-packaging \
    python3-pip \
    python3-pygccxml \
    python3-uhd \
    python3-zmq \
    sudo \
    uhd-host \
    unzip \
    wget
RUN dpkg -r --force-depends python3-numpy && pip install --break-system-packages "numpy>=2.0.1"
RUN /usr/bin/uhd_images_downloader -t "b2|usb"
WORKDIR /root
# https://wiki.gnuradio.org/index.php/GNU_Radio_3.9_OOT_Module_Porting_Guide
RUN git clone --depth 1 https://github.com/gnuradio/volk -b v3.1.2
RUN git clone --depth 1 https://github.com/pothosware/SoapySDR -b soapy-sdr-0.8.1
WORKDIR /root/volk/build
RUN git submodule update --init
RUN cmake .. && make -j "$(nproc)" && make install
WORKDIR /root/SoapySDR/build
RUN cmake .. && make -j "$(nproc)" && make install
